spring:
  application:
    name: subscription-service
  data:
    redis:
      host: 10.0.5.2
      port: 6397
      password:
      database: 0

app:
  backend-url: http://127.0.0.1:8080/
  invalid-time-minutes: 5

server:
  port: 8081