spring:
  application:
    name: subscription-service
  # Redis连接
  data:
    redis:
      host: 10.0.5.2
      port: 6397
      # 密码 没有则留空
      password:
      # 数据库 0-15中选择
      database: 0

app:
  # 后端地址
  backend-url: http://127.0.0.1:8080/
  # token失效时间 单位分
  invalid-time-minutes: 5

# 运行端口
server:
  port: 8081